language: go
go:
  - tip

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get

script:
  - go vet
  - gofmt -e -d *.go
  - go build
  - goveralls -service=travis-ci

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
